version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: parcel-plugin-static-files-copy
    versions:
    - 2.5.1
  - dependency-name: three
    versions:
    - 0.126.1
