name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull && npm install && rm -R ./dist && npx parcel build index.html && sudo /usr/sbin/service nginx restart